sudo: required
services: docker

language: go
go:
  - 1.6.2

before_install:
  - sudo apt-get update -qq && sudo apt-get -y --force-yes -o Dpkg::Options::="--force-confnew" install $APT_DOCKER_PKG && docker -v
  - docker -v
  - docker login --help
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
  - go build .
  - git_ref=$(git symbolic-ref HEAD 2>/dev/null)
  - docker build --build-arg gitref=$git_ref -t rightscale/oauth2_proxy:$TRAVIS_BRANCH -t rightscale/oauth2_proxy:latest .
  - docker push rightscale/oauth2_proxy:$TRAVIS_BRANCH
  - docker push rightscale/oauth2_proxy:latest

sudo: false
notifications:
  email: false

